### ISSUE TITLE
[RFC] PR 自动构建 bot

### ISSUE THREAD

**Issue by xcodebuild** [xcodebuild/iProxy#5]
Pull Request 更新时自动触发 Github Action 构建一个测试版本，然后把测试包恢复到 Pull Request 下，方便进行测试。

预计可能用到：https://github.com/marketplace/actions/reginald-a-pull-request-review-bot

测试包构建的时候改个名字和版本即可和原版本的数据不冲突

**Comment by xcodebuild** [comment]
实现上比较麻烦，另外 PR 构建有些麻烦，如果是三方提交的 PR 自动触发可以上传文件的 build，意味着可能会做更多不安全的事情。

我们做一个 `master` 分支的 `nightly build` 就可以了。

**Comment by 7sDream** [comment]
可以考虑用 [bors bot](https://github.com/apps/bors)。

这个的原理是，如果一个 PR 被管理员回复了 `bors r+`，会自动把 PR 合到一个特殊的分支 `trying`，然后跑 Github Actions，如果全都成功，才会把 PR 的分支合到 master 上去。

如果回复的是 `bors try`，就只会执行合 `trying` 和跑 Github Action，然后把跑完的链接回复到 PR 里。

一个 PR 例子：https://github.com/7sDream/fontfor/pull/39，我一般就直接 `r+` 了。

但是配置起来可能稍微有点麻烦，可以参考之前我的一个项目配置这个机器人的 [PR](https://github.com/7sDream/fontfor/pull/32)。

**Comment by xcodebuild** [comment]
PR 自动构建搞定了，https://github.com/xcodebuild/iproxy/pull/4 是第一个例子

**Comment by xcodebuild** [comment]
Nightly 的每夜构建也 ok 了（虽然今天不知道为什么没触发），下载地址在 https://nightly.link/xcodebuild/iProxy/workflows/nightly/master
