### ISSUE TITLE
什么破玩意，一坑未完又开一坑？

### ISSUE THREAD

**Issue by lizy0329** [xcodebuild/iProxy#63]
Lightproxy 诸多 bug 还未修复就 fork 一个想借尿遁？

**Comment by shouhuanxiaoji** [comment]
作者从lightproxy所在团队离职了。。没有了项目参与权限和意义，只能fork一下继续维护

**Comment by lizy0329** [comment]
离职前好歹说说当前 lightproxy 的情况，这离职身后一堆屎也是没谁了

**Comment by shouhuanxiaoji** [comment]
不是当事人的话，还是不要开喷的吧。。也许当时作者有很多情况无法明说

**Comment by lizy0329** [comment]
算了，当自己犯贱用了阿里的开源 -_-

**Comment by shouhuanxiaoji** [comment]
在这反馈问题一样的啊

**Comment by lizy0329** [comment]
> 在这反馈问题一样的啊

当然是不一样的，不是因为这个 xcodebuild 创造了这个开源工具我们使用，是因为阿里开源，所以我们使用，希望作者能够做些说明，让我们在 lightProxy 提的 mr 有人处理下

**Comment by shouhuanxiaoji** [comment]
你的意思是，你是看到大厂的工具才去使用，而不是因为软件本身优秀？

**Comment by xcodebuild** [comment]
我无法干预前公司去做什么事情哈，有什么问题可以开 issue，也可以 PR。

> > 在这反馈问题一样的啊
> 
> 当然是不一样的，不是因为这个 xcodebuild 创造了这个开源工具我们使用，是因为阿里开源，所以我们使用，希望作者能够做些说明，让我们在 lightProxy 提的 mr 有人处理下
