### ISSUE TITLE
macOS 合盖后再打开会提示『您要应用程序 xxxx 接受传入网络连接吗？』

### ISSUE THREAD

**Issue by nailuoGG** [xcodebuild/iProxy#76]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/4554827/177935130-90a29360-8f45-4ab5-8b0d-88c6532ea132.png">

系统信息：

macOS Monterey 12.4

iProxy 信息，使用master分支本地编译的最新版本

**Comment by songyazhao** [comment]
+1

**Comment by lorcannn** [comment]
+1
